name: Playwright Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 10
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: '1.1.29'
      - name: Install dependencies
        run: bun i
      - run: bun run build
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    permissions:
      deployments: write
      contents: read
    uses: './.github/workflows/on_main_deploy_to_vercel.yaml'
    secrets: inherit
